export interface GeneralStylesProps {
    display?: string,
    justifyContent?: string,
    alignItems?: string,
    alignSelf?: string,
    textAlign?: string,
    fontFamily?: string,
    backgroundColor?: string,
    width?: string | number,
    border?: string,
    fontWeight?: number,
    marginTop?: number,
    marginRight?: number,
    marginBottom?: number,
    marginLeft?: number,
    paddingTop?: number,
    paddingRight?: number,
    paddingBottom?: number,
    paddingLeft?: number,
    padding?: number,
}